from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
DATABASE_PATH = DATA_DIR / "stocks.db"

STOCK_SYMBOLS = {
    "INFY": "INFY.NS",
    "TCS": "TCS.NS",
    "RELIANCE": "RELIANCE.NS",
}

DEFAULT_LOOKBACK_DAYS = 30
ALLOWED_LOOKBACK_DAYS = {7, 30, 90}
TRADING_YEAR_WINDOW = 252
MOVING_AVERAGE_WINDOW = 7
VOLATILITY_WINDOW = 14
CACHE_TTL_SECONDS = 600
PREDICTION_TRAINING_WINDOW = 90
PREDICTION_FORECAST_DAYS = 7
MIN_PREDICTION_POINTS = 10
TOP_MOVERS_LIMIT = 3
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
GENERIC_API_ERROR_MESSAGE = "An unexpected error occurred while processing the request."
